### ISSUE TITLE
Holiday

### ISSUE THREAD

**Issue by amandashort** [dsi-principles-prog/midterm-amandashort#1]
Create a new function that will be a binary indicator of the holiday variable. 1 would denote that it is a holiday and 0 would be for non-holidays. The holiday variable will either list the name of the holiday or otherwise will list "none" if the day was not a holiday.

This is the assert that I used to test the function: assert(in_set(0,1), holiday_binary) 

And this is what the output looks like:
![image](https://user-images.githubusercontent.com/54040000/67628127-48d02100-f837-11e9-8726-36aad0167d57.png)

**Comment by Jiabing-Ruan** [comment]
finished
