### ISSUE TITLE
Weekday

### ISSUE THREAD

**Issue by amandashort** [dsi-principles-prog/midterm-amandashort#2]
Create a function that tells the day of the week using the date variable. The date is already in the correct format and can be used to identify the day of week. It would be best to list out the actual day rather than a number. 

This is the assert statement that I used to check the function: assert(in_set("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"), day_of_week)

This is what the output looks like:
<img width="102" alt="Screen Shot 2019-10-26 at 9 12 24 PM" src="https://user-images.githubusercontent.com/54040000/67628275-c9435180-f838-11e9-959d-0c30f868ced8.png">

**Comment by Jiabing-Ruan** [comment]
finished
